import NavBar from '@/components/NavBar';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />
      <main>
        <h1>Tes</h1>
      </main>
    </div>
  );
};

export default Home;
